### ISSUE TITLE
could not load file 'pry'

### ISSUE THREAD

**Issue by irvinowens** [jamestunnell/spcore#2]
I think there will need to be a development dependency in the Gemfile for running local rspec tests when using this in rails.  I added it to my Gemfile as

<pre>
gem 'pry', :group => :development
</pre>

And it works OK...  If I get around to it, I'll submit a pull request.

**Comment by jamestunnell** [comment]
If that helps you run in Rails, you're welcome to add that change. Also, I'm curious what you're using the gem for.

**Comment by irvinowens** [comment]
ATM I'm just using it for down-sampling and over-sampling wav files with the WaveFile gem.  I found it via your comments on that repo, but some of the other transforms appear useful.
